### ISSUE TITLE
rootfs ?

### ISSUE THREAD

**Issue by applemuncy** [ubports/build-scripts#3]
Also useful to see would be the script that pulls and repackages the rootfs.

**Comment by mariogrip** [comment]
Here are those: https://launchpad.net/ubuntu-system-image they are made by canonical.

**Comment by applemuncy** [comment]
???
No way.  I do not think you understood what I was asking. 

Are you saying that system-server does not pull an image from http://cdimage.ubuntu.com/ubuntu-touch/vivid/daily-preinstalled/  and repacks into xxx.tar.xz  ?

**Comment by mariogrip** [comment]
The https://launchpad.net/ubuntu-system-image tool does all that.

**Comment by applemuncy** [comment]
So it's handled my a complex python script that I assume chugs along rather nicely after it's set up.  
So input => python + setup => output.
What in the setup ?
