### ISSUE TITLE
Update build script for Halium ports

### ISSUE THREAD

**Issue by Flohack74** [ubports/build-scripts#7]
The current build script cannot work with a Halium port at all.

**Comment by xxxyangyi** [comment]
how to build Halium port now ? @Flohack74

**Comment by xxxyangyi** [comment]
how to build Halium port now ?  where is  current build script ? @Flohack74
 thanks

**Comment by Flohack74** [comment]
I am pretty much sure this has been resolved. AS we are building now for halium devices in our CI.
